{
  "contest": 344,
  "handle": "zhaojie",
  "risk": "3",
  "title": "A cache that times out can be recovered.",
  "issueId": 44,
  "issueUrl": "https://github.com/code-423n4/2024-03-phala-network-findings/issues/44"
}